name: Build image
on:
  push:
    branches:
      - "**"
    paths:
      - "mail/**"


permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Build
        run: |
          echo "done" 1>&2
